site_name: GitHub Gem Seeker Documentation
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top

extra_css:
  - stylesheets/extra.css

plugins:
  - search
